-- 005_launch_readiness.sql
--
-- Purpose:
-- 1) Remove demo Java course content from production path.
-- 2) Extend users profile model for launch (first_name, last_name, nickname, public_id).
-- 3) Add worker processing retry counter for submissions.

-- Remove demo learning content seeded for Java showcase.
DELETE FROM courses
WHERE slug = 'java-start';

-- Remove synthetic training metrics generated by demo submissions.
DELETE FROM xp_events
WHERE reason = 'task_accepted';

DELETE FROM user_achievements;

UPDATE users
SET xp = 0,
    level = 1,
    streak = 0,
    updated_at = NOW()
WHERE role <> 'admin';

-- Track worker processing retries separately from student attempts.
ALTER TABLE submissions
    ADD COLUMN IF NOT EXISTS processing_attempts INTEGER NOT NULL DEFAULT 0;

-- Launch profile fields.
ALTER TABLE users
    ADD COLUMN IF NOT EXISTS first_name TEXT,
    ADD COLUMN IF NOT EXISTS last_name TEXT,
    ADD COLUMN IF NOT EXISTS nickname TEXT,
    ADD COLUMN IF NOT EXISTS public_id TEXT;

WITH prepared AS (
    SELECT
        u.id,
        COALESCE(
            NULLIF(
                LOWER(
                    REGEXP_REPLACE(
                        COALESCE(NULLIF(u.username, ''), SPLIT_PART(u.email, '@', 1), 'user'),
                        '[^a-zA-Z0-9_]+',
                        '_',
                        'g'
                    )
                ),
                ''
            ),
            'user'
        ) AS base_nickname,
        ROW_NUMBER() OVER (
            PARTITION BY LOWER(
                COALESCE(
                    NULLIF(
                        REGEXP_REPLACE(
                            COALESCE(NULLIF(u.username, ''), SPLIT_PART(u.email, '@', 1), 'user'),
                            '[^a-zA-Z0-9_]+',
                            '_',
                            'g'
                        ),
                        ''
                    ),
                    'user'
                )
            )
            ORDER BY u.created_at, u.id
        ) AS nickname_rank
    FROM users u
),
normalized AS (
    SELECT
        p.id,
        CASE
            WHEN p.nickname_rank = 1 THEN p.base_nickname
            ELSE p.base_nickname || '_' || p.nickname_rank
        END AS generated_nickname
    FROM prepared p
)
UPDATE users u
SET
    first_name = COALESCE(NULLIF(u.first_name, ''), 'User'),
    last_name = COALESCE(u.last_name, ''),
    nickname = COALESCE(NULLIF(u.nickname, ''), n.generated_nickname),
    public_id = COALESCE(
        NULLIF(u.public_id, ''),
        'LC-' || UPPER(SUBSTRING(REPLACE(u.id::text, '-', '') FOR 10))
    )
FROM normalized n
WHERE u.id = n.id;

ALTER TABLE users
    ALTER COLUMN first_name SET NOT NULL,
    ALTER COLUMN last_name SET NOT NULL,
    ALTER COLUMN nickname SET NOT NULL,
    ALTER COLUMN public_id SET NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_users_nickname_unique_ci
    ON users (LOWER(nickname));

CREATE UNIQUE INDEX IF NOT EXISTS idx_users_public_id_unique
    ON users (public_id);
